name: Token
on: [push,workflow_dispatch]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Run 1
        run: |
          if [ -n ${{ github.token }} ]; then
            echo yes
          else 
            echo no
          fi
      - name: Run 2
        run: |
          if [ -n ${{ secrets.GITHUB_TOKEN }} ]; then
            echo yes
          else 
            echo no
          fi
      - name: Run 3
        run: |
          if [ ${{ github.token }} = ${{ secrets.GITHUB_TOKEN }} ]; then
            echo yes
            if [ ${{ github.token }} = ${{ secrets.GH_TOKEN }} ]; then
              echo yes
            else
              echo no
            fi
          else 
            echo no
          fi
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: 0001
          body: TEST
          token: ${{github.token}}
